# Generated by Django 6.0.2 on 2026-02-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_productroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRoom',
            new_name='Products',
        ),
    ]
