# Generated by Django 6.0.2 on 2026-02-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo_price',
        ),
    ]
