# Generated by Django 6.0.2 on 2026-02-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_product_images_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
