# Generated by Django 6.0.2 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='bedroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='guest_number',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
