# Generated by Django 6.0.2 on 2026-02-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_product_amenities_product_bathroom_product_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promot_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
