# Generated by Django 6.0.2 on 2026-03-17 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_product_guest_number_alter_product_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('stay_type', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promot_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('bedroom', models.IntegerField(default=1)),
                ('guest_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bathroom', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('images', models.ImageField(null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='room.amenities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
