# Generated by Django 6.0.2 on 2026-03-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_amenities_remove_orders_product_room_orders_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=200),
        ),
    ]
