# Generated by Django 6.0.2 on 2026-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='localization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
