# Generated by Django 6.0.2 on 2026-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_user_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
