# Generated by Django 6.0.2 on 2026-03-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_alter_orders_delevery_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Amount',
            new_name='amount',
        ),
    ]
