# Generated by Django 6.0.2 on 2026-03-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_rename_amount_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='room',
        ),
        migrations.CreateModel(
            name='OrdeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='room.orders')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='room.room')),
            ],
        ),
    ]
