# Generated by Django 6.0.2 on 2026-03-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_remove_orders_room_ordeitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeItems',
            new_name='OrderItems',
        ),
    ]
