# Generated by Django 6.0.2 on 2026-03-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_rename_ordeitems_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
