# Generated by Django 6.0.2 on 2026-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_rename_amount_orders_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, default='active', null=True),
        ),
    ]
