# Generated by Django 6.0.2 on 2026-04-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'Amenities', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'OrderItems', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
